update scripts and workflows

diff --git a/.github/workflows/next-deploy.yml b/.github/workflows/next-deploy.yml
--- a/.github/workflows/next-deploy.yml
+++ b/.github/workflows/next-deploy.yml
@@ -57,8 +57,8 @@ jobs:
         id: extract_repo
         run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
 
-      - name: Debug
-        run: echo '${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}'
+      - name: Save image to environment variable
+        run: echo "IMAGE=${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_ENV
 
       - name: Deploy to containerapp
         uses: azure/CLI@v1
@@ -66,7 +66,7 @@ jobs:
           inlineScript: |
             az config set extension.use_dynamic_install=yes_without_prompt
             az containerapp registry set -n ${{ env.AZURE_CONTAINER_APP_NAME }} -g ${{ env.AZURE_GROUP_NAME }} --server ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }} --debug
-            az containerapp update -n ${{ env.AZURE_CONTAINER_APP_NAME }} -g ${{ env.AZURE_GROUP_NAME }} --image ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} --debug
+            az containerapp update -n ${{ env.AZURE_CONTAINER_APP_NAME }} -g ${{ env.AZURE_GROUP_NAME }} --image ${{ env.IMAGE }} --debug
 
       - name: Get FQDN of the deployed containerapp
         uses: azure/CLI@v1
@@ -75,10 +75,37 @@ jobs:
             FQDN=$(az containerapp show -n ${{ env.AZURE_CONTAINER_APP_NAME }} -g ${{ env.AZURE_GROUP_NAME }} --query configuration.ingress.fqdn -o tsv)
             echo "FQDN=${FQDN}" >> $GITHUB_ENV
 
-      - name: Update GitHub OAuth app redirect URL
+      - name: Get container image of the active revision
+        uses: azure/CLI@v1
+        with:
+          inlineScript: |
+            IMAGE=$(az containerapp revision show -n ${{ env.AZURE_CONTAINER_APP_NAME }} -g ${{ env.AZURE_GROUP_NAME }} --query containers[0].image -o tsv)
+            echo "ACTIVE_IMAGE=${IMAGE}" >> $GITHUB_ENV
+
+      - name: Debug
         run: |
-          curl -X PATCH \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            -H "Accept: application/vnd.github.v3+json" \
-            https://api.github.com/applications/${{ secrets.GITHUB_CLIENT_ID }}/callback \
-            -d '{"callback_url": "https://${{ env.FQDN }}/login/github/callback"}'
+          echo "The FQDN is ${{ env.FQDN }}"
+          echo "The active   container image is ${{ env.ACTIVE_IMAGE }}"   
+          echo "The expected container image is ${{ env.IMAGE }}"         
+
+
+      - name: Check if image exists in ACR
+        run: |
+          IMAGE_TAG=${{ github.sha }}
+          REPO=${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}
+          TAGS=$(az acr repository show-tags --name ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }} --repository $REPO --output tsv)
+          if echo "$TAGS" | grep -q "$IMAGE_TAG"; then
+            echo "Image $REPO:$IMAGE_TAG exists in ACR."
+          else
+            echo "Error: Image $REPO:$IMAGE_TAG does not exist in ACR."
+            exit 1
+          fi
+
+      - name: Compare active image to expected image
+        run: |
+          if [ "${{ env.ACTIVE_IMAGE }}" != "${{ env.IMAGE }}" ]; then
+            echo "Error: The active container image does not match the expected image."
+            exit 1
+          else
+            echo "The active container image matches the expected image."
+          fi
